// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.DMS.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.DMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DMSDbContext))]
    partial class DMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dms")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.DMS.Domain.Aggregates.Document.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<string>("FileLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_label");

                    b.Property<string>("LinkId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("link_id");

                    b.Property<string>("LinkLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link_label");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer")
                        .HasColumnName("link_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_documents_owner_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_documents_tenant_id");

                    b.HasIndex("ValidUntil")
                        .HasDatabaseName("ix_documents_valid_until");

                    b.ToTable("documents", "dms");
                });

            modelBuilder.Entity("SpaceOS.Modules.DMS.Domain.Aggregates.DocumentCategory.DocumentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_categories_tenant_id");

                    b.ToTable("document_categories", "dms");
                });

            modelBuilder.Entity("SpaceOS.Modules.DMS.Domain.Aggregates.Tag.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tags_tenant_id");

                    b.ToTable("tags", "dms");
                });

            modelBuilder.Entity("SpaceOS.Modules.DMS.Domain.Aggregates.Document.Document", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.DMS.Domain.Aggregates.Document.DocumentVersionEntry", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BlobPath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("blob_path");

                            b1.Property<string>("ChangeNote")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("change_note");

                            b1.Property<string>("FileLabel")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_label");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<string>("UploadedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("uploaded_by");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("document_id", "VersionNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_document_versions_document_id_version_number");

                            b1.ToTable("document_versions", "dms");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.OwnsMany("SpaceOS.Modules.DMS.Domain.ValueObjects.DocumentPermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("GrantedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at");

                            b1.Property<Guid>("GrantedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("granted_by_user_id");

                            b1.Property<Guid?>("GrantedToRoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("granted_to_role_id");

                            b1.Property<Guid?>("GrantedToUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("granted_to_user_id");

                            b1.Property<int>("PermissionType")
                                .HasColumnType("integer")
                                .HasColumnName("permission_type");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("document_id", "GrantedToRoleId")
                                .HasDatabaseName("ix_document_permissions_document_id_role");

                            b1.HasIndex("document_id", "GrantedToUserId")
                                .HasDatabaseName("ix_document_permissions_document_id_user");

                            b1.ToTable("document_permissions", "dms");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.Navigation("Permissions");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
