// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.CRM.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260716180438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OpportunityRef")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedTo");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("leads", "crm");
                });

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpectedCloseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("LossReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Probability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedTo");

                    b.HasIndex("TenantId", "LeadId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("opportunities", "crm");
                });

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Lead", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.CRM.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Company")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_company");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "crm");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsMany("SpaceOS.Modules.CRM.Domain.Aggregates.Activity", "Activities", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("lead_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("lead_id");

                            b1.ToTable("lead_activities", "crm");

                            b1.WithOwner()
                                .HasForeignKey("lead_id");
                        });

                    b.OwnsMany("SpaceOS.Modules.CRM.Domain.Aggregates.CrmTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("DueDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsCompleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("lead_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("lead_id");

                            b1.ToTable("lead_tasks", "crm");

                            b1.WithOwner()
                                .HasForeignKey("lead_id");
                        });

                    b.Navigation("Activities");

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Opportunity", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.CRM.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Company")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_company");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities", "crm");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("SpaceOS.Modules.CRM.Domain.ValueObjects.Money", "EstimatedValue", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("estimated_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("estimated_value_currency");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities", "crm");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("SpaceOS.Modules.CRM.Domain.ValueObjects.Money", "FinalValue", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("final_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("final_value_currency");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities", "crm");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsMany("SpaceOS.Modules.CRM.Domain.Aggregates.Activity", "Activities", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("opportunity_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("opportunity_id");

                            b1.ToTable("opportunity_activities", "crm");

                            b1.WithOwner()
                                .HasForeignKey("opportunity_id");
                        });

                    b.OwnsMany("SpaceOS.Modules.CRM.Domain.Aggregates.CrmTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("DueDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsCompleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("opportunity_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("opportunity_id");

                            b1.ToTable("opportunity_tasks", "crm");

                            b1.WithOwner()
                                .HasForeignKey("opportunity_id");
                        });

                    b.Navigation("Activities");

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("EstimatedValue")
                        .IsRequired();

                    b.Navigation("FinalValue");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
