// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Ehs.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Modules.Ehs.Infrastructure.Migrations
{
    [DbContext(typeof(EhsDbContext))]
    [Migration("20260715204959_RiskAssessment5x5Fsm")]
    partial class RiskAssessment5x5Fsm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.HazardousMaterialAggregate.HazardousMaterial", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("CasNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cas_number");

                    b.Property<List<string>>("GhsHazardClasses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ghs_hazard_classes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("QuantityOnSite")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_on_site");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid?>("SdsDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("sds_document_id");

                    b.Property<DateTimeOffset>("SdsExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sds_expires_at");

                    b.Property<DateTimeOffset>("SdsIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sds_issued_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_location_id");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("MaterialId");

                    b.HasIndex("SdsExpiresAt")
                        .HasDatabaseName("ix_hazardous_materials_sds_expires_at");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("ix_hazardous_materials_storage_location_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_hazardous_materials_tenant_id");

                    b.ToTable("hazardous_materials", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.CorrectiveAction", b =>
                {
                    b.Property<Guid>("CorrectiveActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("corrective_action_id");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("CorrectiveActionId");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_corrective_actions_assigned_to");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_corrective_actions_incident_id");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_corrective_actions_source");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_corrective_actions_source_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_corrective_actions_tenant_id");

                    b.ToTable("corrective_actions", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("IncidentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("incident_type");

                    b.Property<DateTimeOffset?>("InvestigatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("investigated_at");

                    b.Property<Guid?>("InvestigatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("investigated_by");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("IncidentId");

                    b.HasIndex("IncidentDate")
                        .HasDatabaseName("ix_incidents_incident_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_incidents_tenant_id");

                    b.ToTable("incidents", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.LocationAggregate.EhsLocation", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_location_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("LocationId");

                    b.HasIndex("ParentLocationId")
                        .HasDatabaseName("ix_locations_parent_location_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_locations_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locations_tenant_code");

                    b.ToTable("locations", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.PpeAggregate.PpeIssuance", b =>
                {
                    b.Property<Guid>("IssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("issuance_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<Guid>("PpeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ppe_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("ReplacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_at");

                    b.Property<Guid?>("ReplacementIssuanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("replacement_issuance_id");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("IssuanceId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_ppe_issuances_employee_id");

                    b.HasIndex("PpeItemId")
                        .HasDatabaseName("ix_ppe_issuances_ppe_item_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ppe_issuances_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ppe_issuances_tenant_id");

                    b.ToTable("ppe_issuances", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.PpeAggregate.PpeItem", b =>
                {
                    b.Property<Guid>("PpeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ppe_item_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultLifetimeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_lifetime_months");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StandardRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("standard_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PpeItemId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ppe_items_tenant_id");

                    b.ToTable("ppe_items", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskAssessment", b =>
                {
                    b.Property<Guid>("RiskAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("risk_assessment_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<Guid>("AssessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assessed_by");

                    b.Property<string>("HazardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hazard_description");

                    b.Property<string>("Likelihood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("likelihood");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("ReviewDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_due_date");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RiskAssessmentId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_risk_assessments_location_id");

                    b.HasIndex("ReviewDueDate")
                        .HasDatabaseName("ix_risk_assessments_review_due_date");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("ix_risk_assessments_risk_level");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_risk_assessments_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_risk_assessments_tenant_id");

                    b.ToTable("risk_assessments", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.SafetyWalkAggregate.SafetyWalk", b =>
                {
                    b.Property<Guid>("SafetyWalkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("safety_walk_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConductedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("conducted_by");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<List<Guid>>("Participants")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("participants");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SafetyWalkId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_safety_walks_location_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_safety_walks_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_safety_walks_tenant_id");

                    b.ToTable("safety_walks", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.TrainingRecordAggregate.TrainingRecord", b =>
                {
                    b.Property<Guid>("TrainingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("training_record_id");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certificate_number");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issued_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("training_type");

                    b.HasKey("TrainingRecordId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_training_records_employee_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_training_records_expires_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_training_records_tenant_id");

                    b.HasIndex("TrainingType")
                        .HasDatabaseName("ix_training_records_training_type");

                    b.ToTable("training_records", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.CorrectiveAction", b =>
                {
                    b.HasOne("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", null)
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.IncidentInvestigation", "Investigation", b1 =>
                        {
                            b1.Property<Guid>("incident_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("Findings")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("findings");

                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_id");

                            b1.Property<Guid>("IncidentInvestigationId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_investigation_id");

                            b1.Property<Guid>("InvestigatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("investigated_by");

                            b1.Property<string>("Recommendations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("recommendations");

                            b1.Property<string>("RootCause")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("root_cause");

                            b1.HasKey("incident_id");

                            b1.HasIndex("incident_id")
                                .HasDatabaseName("ix_incident_investigations_incident_id");

                            b1.ToTable("incident_investigations", "ehs", t =>
                                {
                                    t.Property("incident_id")
                                        .HasColumnName("incident_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("incident_id");
                        });

                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.IncidentWitness", "Witnesses", b1 =>
                        {
                            b1.Property<Guid>("incident_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("IncidentWitnessId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("incident_witness_id");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("employee_id");

                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_id");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Statement")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("statement");

                            b1.HasKey("incident_id", "IncidentWitnessId");

                            b1.HasIndex("incident_id")
                                .HasDatabaseName("ix_incident_witnesses_incident_id");

                            b1.ToTable("incident_witnesses", "ehs", t =>
                                {
                                    t.Property("incident_id")
                                        .HasColumnName("incident_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("incident_id");
                        });

                    b.Navigation("Investigation");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskAssessment", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskControl", "Controls", b1 =>
                        {
                            b1.Property<Guid>("risk_assessment_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RiskControlId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("risk_control_id");

                            b1.Property<string>("ControlMeasure")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("control_measure");

                            b1.Property<Guid?>("CorrectiveActionId")
                                .HasColumnType("uuid")
                                .HasColumnName("corrective_action_id");

                            b1.Property<DateTimeOffset>("ImplementedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("implemented_at");

                            b1.Property<string>("ResponsiblePerson")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("responsible_person");

                            b1.Property<Guid>("RiskAssessmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("risk_assessment_id");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verified_at");

                            b1.HasKey("risk_assessment_id", "RiskControlId");

                            b1.HasIndex("risk_assessment_id")
                                .HasDatabaseName("ix_risk_controls_risk_assessment_id");

                            b1.ToTable("risk_controls", "ehs", t =>
                                {
                                    t.Property("risk_assessment_id")
                                        .HasColumnName("risk_assessment_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("risk_assessment_id");
                        });

                    b.Navigation("Controls");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.SafetyWalkAggregate.SafetyWalk", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.SafetyWalkAggregate.SafetyWalkFinding", "Findings", b1 =>
                        {
                            b1.Property<Guid>("FindingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("finding_id");

                            b1.Property<Guid?>("CorrectiveActionId")
                                .HasColumnType("uuid")
                                .HasColumnName("corrective_action_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<Guid?>("LinkedRiskAssessmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("linked_risk_assessment_id");

                            b1.Property<string>("PhotoS3Key")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("photo_s3_key");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<bool>("RequiresAction")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_action");

                            b1.Property<Guid>("SafetyWalkId")
                                .HasColumnType("uuid")
                                .HasColumnName("safety_walk_id");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("severity");

                            b1.HasKey("FindingId");

                            b1.HasIndex("SafetyWalkId")
                                .HasDatabaseName("ix_safety_walk_findings_safety_walk_id");

                            b1.ToTable("safety_walk_findings", "ehs");

                            b1.WithOwner()
                                .HasForeignKey("SafetyWalkId");
                        });

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", b =>
                {
                    b.Navigation("CorrectiveActions");
                });
#pragma warning restore 612, 618
        }
    }
}
