// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.QA.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.QA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QADbContext))]
    [Migration("20260718040356_AddTickets")]
    partial class AddTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<Guid?>("ReworkOfInspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rework_of_inspection_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId")
                        .HasDatabaseName("ix_inspections_checkpoint_id");

                    b.HasIndex("ReworkOfInspectionId")
                        .HasDatabaseName("ix_inspections_rework_of_inspection_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inspections_tenant_id");

                    b.ToTable("inspections", "qa");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.QACheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("checkpoint_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriticalLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("critical_level");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_qa_checkpoints_tenant_id");

                    b.ToTable("qa_checkpoints", "qa");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_tickets_assigned_to");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("ix_tickets_reported_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tickets_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tickets_tenant_id");

                    b.ToTable("tickets", "qa");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Inspection", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.QA.Domain.ValueObjects.FailureNote", "FailureNotes", b1 =>
                        {
                            b1.Property<Guid>("inspection_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<string>("FailureType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("failure_type");

                            b1.Property<string>("PhotoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("photo_url");

                            b1.HasKey("inspection_id", "Id");

                            b1.HasIndex("inspection_id")
                                .HasDatabaseName("ix_inspection_defects_inspection_id");

                            b1.ToTable("inspection_defects", "qa");

                            b1.WithOwner()
                                .HasForeignKey("inspection_id");
                        });

                    b.Navigation("FailureNotes");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.QACheckpoint", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.QA.Domain.ValueObjects.InspectionCriteria", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("qa_checkpoint_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<string>("AcceptanceThreshold")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("acceptance_threshold");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("type");

                            b1.HasKey("qa_checkpoint_id", "Id");

                            b1.HasIndex("qa_checkpoint_id")
                                .HasDatabaseName("ix_qa_checkpoint_criteria_qa_checkpoint_id");

                            b1.ToTable("qa_checkpoint_criteria", "qa");

                            b1.WithOwner()
                                .HasForeignKey("qa_checkpoint_id");
                        });

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Ticket", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.QA.Domain.ValueObjects.ResolutionAction", "ResolutionActions", b1 =>
                        {
                            b1.Property<Guid>("ticket_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<string>("ActionType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("action_type");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.HasKey("ticket_id", "Id");

                            b1.ToTable("ticket_resolution_actions", "qa");

                            b1.WithOwner()
                                .HasForeignKey("ticket_id");

                            b1.OwnsOne("SpaceOS.Modules.QA.Domain.ValueObjects.Money", "Cost", b2 =>
                                {
                                    b2.Property<Guid>("ResolutionActionticket_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ResolutionActionId")
                                        .HasColumnType("character varying(36)");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("cost_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("cost_currency");

                                    b2.HasKey("ResolutionActionticket_id", "ResolutionActionId");

                                    b2.ToTable("ticket_resolution_actions", "qa");

                                    b2.WithOwner()
                                        .HasForeignKey("ResolutionActionticket_id", "ResolutionActionId");
                                });

                            b1.Navigation("Cost")
                                .IsRequired();
                        });

                    b.Navigation("ResolutionActions");
                });
#pragma warning restore 612, 618
        }
    }
}
